from flask import Flask, render_template, url_for, flash, redirect
from forms import RegistrationForm, LoginForm


app = Flask(__name__)

app.config['SECRET_KEY'] = '54869a0a55f9b9b8dbd8915596bbf36b'

'''
   the secret key is generated by 
   >>> import secrets 
   >>> secrets.token_hex(16)
   // now a 16 byte code will be generated randomly  
'''

posts = [
    {
        'author': 'Saranya Maity',
        'title': 'How to Excel in Competitive Programming',
        'content': 'Go to my Github profile github.com/saranyamaity2000',
        'date': 'Aug 9, 2021'
    },
    {
        'author': 'Swagato Bag',
        'title': 'Placed in HRC!',
        'content': 'I am very glad to say, after a lot work experience finally placed in HRC',
        'date': 'Aug 20, 2021'
    }
]


@app.route("/")  # these are decorators
@app.route("/home")
def home():
    return render_template('home.html', posts=posts)


@app.route("/about")
def about():
    return render_template('about.html', title='about')


@app.route("/register", methods=['GET', 'POST'])  # Get request and POST request
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        flash(f'Account Created for {form.username.data}!', 'success')  # we have used f string for ease
        return redirect(url_for('home'))
    return render_template('register.html', title='Register', form=form)


@app.route("/login")
def login():
    form = LoginForm()
    return render_template('login.html', title='Login', form=form)


# most of the time we will be using
# export FLASK_APP='main.py'
# flask run
if __name__ == '__main__':  # useful when we use direct run
    app.run(debug=True)
